### ISSUE TITLE
install fails when install sphinx at the same time

### ISSUE THREAD

**Issue by larsbijl** [fraoustin/sphinx_fontawesome#3]
When installing sphinx and sphinx_fontawesome it fails with the error.

create an requirements.txt with sphinx and sphinx_fontawesome

pip install -r requirements.txt

```
Collecting sphinx_fontawesome==0.0.3 (from -r requirements.txt (line 37))
  Downloading sphinx_fontawesome-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2vuerlgv/sphinx-fontawesome/setup.py", line 7, in <module>
        import sphinx_fontawesome
      File "/tmp/pip-build-2vuerlgv/sphinx-fontawesome/sphinx_fontawesome/__init__.py", line 9, in <module>
        from sphinx import addnodes
    ImportError: No module named 'sphinx'
```

this is because sphinx is not fully installed yet. 

the `addnodes` function is not being used in the module so maybe it can just be removed?

**Comment by hdd** [comment]
Hi Same issue here.

**Comment by fraoustin** [comment]
Add sphinx in requirement.txt -> I generate new version 0.0.4

**Comment by larsbijl** [comment]
Hey @fraoustin this doesn't fix the issue. I think it's because during the `setup.py egg_info` call it tries to load the module. which has the `import sphinx` but this is not installed you as pip has only downloaded the packages.

**Comment by fraoustin** [comment]
Hey add fix can you test (version 0.0.5)

**Comment by larsbijl** [comment]
```
Collecting sphinx_fontawesome==0.0.5 (from -r requirements.txt (line 37))
  Downloading sphinx_fontawesome-0.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3_lbkpk2/sphinx-fontawesome/setup.py", line 7, in <module>
        import sphinx_fontawesome
      File "/tmp/pip-build-3_lbkpk2/sphinx-fontawesome/sphinx_fontawesome/__init__.py", line 9, in <module>
        from sphinx import addnodes
    ImportError: No module named 'sphinx'
 ```

**Comment by larsbijl** [comment]
to test it you can use docker. this `Dockerfile` shows the issue

```
FROM python:3.5

RUN pip install --no-cache-dir sphinx sphinx_fontawesome==0.0.5 
```

to run 

```
lars@lars:/tmp/test$ docker build .
Sending build context to Docker daemon 2.048 kB
Step 1/2 : FROM python:3.5
 ---> 81006ef783d0
Step 2/2 : RUN pip install --no-cache-dir sphinx sphinx_fontawesome==0.0.5
 ---> Running in 1fc52d838c0e
Collecting sphinx
  Downloading Sphinx-1.6.3-py2.py3-none-any.whl (1.9MB)
Collecting sphinx_fontawesome==0.0.5
  Downloading sphinx_fontawesome-0.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-q6sjl_33/sphinx-fontawesome/setup.py", line 7, in <module>
        import sphinx_fontawesome
      File "/tmp/pip-build-q6sjl_33/sphinx-fontawesome/sphinx_fontawesome/__init__.py", line 9, in <module>
        from sphinx import addnodes
    ImportError: No module named 'sphinx'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-q6sjl_33/sphinx-fontawesome/
The command '/bin/sh -c pip install --no-cache-dir sphinx sphinx_fontawesome==0.0.5' returned a non-zero code: 1
```

**Comment by fraoustin** [comment]
add problem with call sphinx-fontawesome module. Add version 0.0.6 in setup.py can not call the module

**Comment by larsbijl** [comment]
Works! thanks
